### ISSUE TITLE
Hook overload complex function crash

### ISSUE THREAD

**Issue by 3asm** [frida/frida-gum#141]
Hi,

I'm trying the hook the following method with this sample script:

``` javascript
var klass = Dalvik.use("android.database.sqlite.SQLiteQueryBuilder");

klass.query.overload("android.database.sqlite.SQLiteDatabase", "[Ljava.lang.String;", "java.lang.String", "[Ljava.lang.String;", "java.lang.String", "java.lang.String", "java.lang.String", "java.lang.String", "android.os.CancellationSignal").implementation = function() {
send("Args: " + Array.prototype.join.call(arguments, ":") + " ;this: " + this.query.overload("android.database.sqlite.SQLiteDatabase", "[Ljava.lang.String;", "java.lang.String", "[Ljava.lang.String;", "java.lang.String", "java.lang.String", "java.lang.String", "java.lang.String", "android.os.CancellationSignal").apply(this, arguments));
                this.query.overload("android.database.sqlite.SQLiteDatabase", "[Ljava.lang.String;", "java.lang.String", "[Ljava.lang.String;", "java.lang.String", "java.lang.String", "java.lang.String", "java.lang.String", "android.os.CancellationSignal").apply(this, arguments);
        };
```

This hook should give the rest of execution the normal way after printing parameters, however this is crashing the requester done using a content provider:

``` java
Error while accessing provider:com.android.insecurebankv2.TrackUserContentProvider
java.lang.NullPointerException: Attempt to invoke interface method 'void android.database.Cursor.setNotificationUri(android.content.ContentResolver, android.net.Uri)' on a null object reference
    at android.os.Parcel.readException(Parcel.java:1546)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
    at android.content.ContentProviderProxy.query(ContentProviderNative.java:420)
    at com.android.commands.content.Content$QueryCommand.onExecute(Content.java:535)
    at com.android.commands.content.Content$Command.execute(Content.java:417)
    at com.android.commands.content.Content.main(Content.java:605)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
```

Am I doing something wrong or is there a bug in the code ?

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
