### ISSUE TITLE
Process terminated when enumerating imports

### ISSUE THREAD

**Issue by koxu1996** [frida/frida-gum#261]
## Steps to reproduce
1. Create simple C program:
```
#include <stdio.h>
#include <unistd.h>

void f(int n)
{
    printf ("Number: %d\n", n);
}

int main (int argc, char * argv[])
{
    int i = 0;
    printf ("f() is at %p\n", f);
    while (1)
    {
        f(i++);
        sleep (1);
    }
}
```
2. Compile it and run
```
$ gcc hello.c -o hello
$ ./hello
```
3. Run frida and enumerate modules:
```
$ frida hello
[Local::hello]-> Process.enumerateModules({onMatch: function(module){console.log("[MODULE] " +
module.name)},onComplete:function(){console.log("Finished!");}})
[MODULE] hello
[MODULE] libm-2.26.so
[MODULE] librt-2.26.so
[MODULE] libdl-2.26.so
[MODULE] libresolv-2.26.so
[MODULE] frida-agent-64.so
[MODULE] libpthread-2.26.so
[MODULE] libc-2.26.so
[MODULE] ld-2.26.so
Finished!
```
4. Enumerate imports from module _hello_:
```
[Local::hello]-> Module.enumerateImports("hello",{onMatch:function(imp){console.log("[IMPORT] "+imp.name)},onComplete:function(){console.log("Finished!");}})
Traceback (most recent call last):
  File "/home/andrew/.virtualenvs/frida/bin/frida", line 11, in <module>
    sys.exit(main())
  File "/home/andrew/.virtualenvs/frida/lib/python3.6/site-packages/frida/repl.py", line 686, in main
    app.run()
  File "/home/andrew/.virtualenvs/frida/lib/python3.6/site-packages/frida/application.py", line 163, in run
    self._reactor.run()
  File "/home/andrew/.virtualenvs/frida/lib/python3.6/site-packages/frida/application.py", line 388, in run
    self._run_until_return(self)
  File "/home/andrew/.virtualenvs/frida/lib/python3.6/site-packages/frida/repl.py", line 254, in _process_input
    if not self._eval_and_print(expression):
  File "/home/andrew/.virtualenvs/frida/lib/python3.6/site-packages/frida/repl.py", line 260, in _eval_and_print
    (t, value) = self._evaluate(expression)
  File "/home/andrew/.virtualenvs/frida/lib/python3.6/site-packages/frida/repl.py", line 416, in _evaluate
    result = self._script.exports.evaluate(text)
  File "/home/andrew/.virtualenvs/frida/lib/python3.6/site-packages/frida/core.py", line 425, in method
    return script._rpc_request('call', js_name, args)
  File "/home/andrew/.virtualenvs/frida/lib/python3.6/site-packages/frida/core.py", line 345, in _rpc_request
    self.post(message)
  File "/home/andrew/.virtualenvs/frida/lib/python3.6/site-packages/frida/core.py", line 307, in post
    self._impl.post(raw_message, **kwargs)
frida.TransportError: the connection is closed
Process terminated
```
5. Now _hello_ process is terminated with `Segmentation fault (core dumped)`

**Comment by oleavr** [comment]
Fixed in the latest version of Frida (10.6.50). Thanks for reporting!

**Comment by oleavr** [comment]
@koxu1996 Ah, thanks! Which exact Linux distro and version is this on?

**Comment by koxu1996** [comment]
I am using Arch Linux x64 with kernel 4.14.15-1.

**Comment by Lawouach** [comment]
Hello, as an FYI, got the same issue when running frida-discover, the target process is terminated. On Ubuntu 18.04 with Python 3.6 and frida 11.0.3.

**Comment by oleavr** [comment]
This was fixed a while ago. (Note that `frida-discover` crashing the process is definitely an unrelated issue.)

**Comment by koxu1996** [comment]
@oleavr I don't get it... this is second time that you are closing my issue and it is not fixed again. I checked latest Frida and there is still _Segmentation fault_, so please reopen issue.

**Comment by oleavr** [comment]
@koxu1996 Ah I just looked at the date and remembered I had fixed an issue like that in the meantime. I'm spread too thin, so complaining doesn't do much good – please help us improve Frida instead of contributing negativity.
