### ISSUE TITLE
A few building errors

### ISSUE THREAD

**Issue by P-Sc** [frida/frida-gum#541]
I've come across a few problems when trying to build frida-gum. I could resolve some of them.

1. **"pthread" not linked**: Can be resolved by adding `depedency('threads')` in `meson.build`
2. **frida-compile not found**: `generate-runtime.py` fails to find `bindings/gumjs/node_modules/.bin/frida-compile`. Can be resolved by `npm install frida-compile` in `bindings/gumjs`. I don't know if this is the intended way, though.
3. **`#include <libdwarf.h>` fails**: Newer versions of libdwarf need `#include <libdwarf/libdwarf.h>`. 
4. **gum not linked with libfrida-gum-heap**: I couldn't find the root cause for this one
5. **`FRIDA_VERSION` causes error**: Maybe it's not defined anywhere? See log
6. **Permission error**: Might be linked to the other problems

<details>
<summary>Meson log</summary>

```
The Meson build system
Version: 0.57.1
Source dir: /home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum
Build dir: /home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir
Build type: native build
Project name: frida-gum
Project version: 1.0.0
C compiler for the host machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.36.1
C++ compiler for the host machine: c++ (gcc 10.2.0 "c++ (GCC) 10.2.0")
C++ linker for the host machine: c++ ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking if "pointer authentication" compiles: NO (cached)
Checking if "compiling for macOS" compiles: NO (cached)
Checking if "compiling for iOS" compiles: NO (cached)
Has header "android/api-level.h" : NO (cached)
Has header "elf.h" : YES (cached)
Has header "link.h" : YES (cached)
Has header "stdint.h" : YES (cached)
Has header "sys/auxv.h" : YES (cached)
Has header "sys/elf.h" : YES (cached)
Has header "asm/ptrace.h" : YES (cached)
Has header "sys/user.h" : YES (cached)
Checking if "asm/prctl.h is available" compiles: YES (cached)
Checking for type "long double" : YES (cached)
Checking for type "long long int" : YES (cached)
Checking for type "unsigned long long int" : YES (cached)
Checking if "compiling for glibc" compiles: YES (cached)
Checking for function "log2" : YES (cached)
Checking whether type "struct mallinfo" has member "arena" : YES (cached)
Dependency glib-2.0 found: YES 2.66.7 (cached)
Dependency gobject-2.0 found: YES 2.66.7 (cached)
Dependency gio-2.0 found: YES 2.66.7 (cached)
Dependency capstone found: YES 5.0.0 (cached)
Dependency libffi found: YES 3.3 (cached)
Dependency liblzma found: YES 5.2.5 (cached)
Dependency threads found: YES unknown (cached)
Checking if "compiling with shared GLib" with dependency glib-2.0 compiles: YES (cached)
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Checking for function "g_thread_set_callbacks" with dependency glib-2.0: NO (cached)
Checking for function "ffi_set_mem_callbacks" with dependency libffi: NO (cached)
Dependency libunwind found: YES 1.5.0 (cached)
Dependency libelf found: YES 0.183 (cached)
Has header "libdwarf/libdwarf.h" : YES (cached)
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Found CMake: /usr/bin/cmake (3.19.6)
Run-time dependency gioopenssl found: NO (tried pkgconfig and cmake)
Dependency quickjs skipped: feature quickjs disabled
Dependency v8 found: YES 8.7.220.25 (cached)
Dependency gio-unix-2.0 found: YES 2.66.7 (cached)
Dependency json-glib-1.0 found: YES 1.6.2 (cached)
Dependency tcc found: YES 4.0.2 (cached)
Dependency sqlite3 found: YES 3.34.1 (cached)
Dependency libsoup-2.4 found: YES 2.72.0 (cached)
Configuring config.h using configuration
Program glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency gobject-introspection-1.0 found: YES 1.66.1 (cached)
Dependency gobject-introspection-1.0 found: YES 1.66.1 (cached)
Program g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Dependency gobject-introspection-1.0 found: YES 1.66.1 (cached)
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Program generate-bindings.py found: YES (/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs/generate-bindings.py)
Program generate-runtime.py found: YES (/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs/generate-runtime.py)
Build targets in project: 19

Option cpp_rtti is: false [default: false]
Found ninja-1.10.2 at /usr/bin/ninja
```
</details>

Error logs:
<details>
<summary>1. pthread not linked </summary>

```
[2/52] Linking target gum/libfrida-gum-1.0.so
FAILED: gum/libfrida-gum-1.0.so 
cc  -o gum/libfrida-gum-1.0.so gum/libfrida-gum-1.0.so.p/meson-generated_.._gumenumtypes.c.o gum/libfrida-gum-1.0.so.p/gum.c.o gum/libfrida-gum-1.0.so.p/gumapiresolver.c.o gum/libfrida-gum-1.0.so.p/gumbacktracer.c.o gum/libfrida-gum-1.0.so.p/gumcloak.c.o gum/libfrida-gum-1.0.so.p/gumcodeallocator.c.o gum/libfrida-gum-1.0.so.p/gumcodesegment.c.o gum/libfrida-gum-1.0.so.p/gumdarwinmodule.c.o gum/libfrida-gum-1.0.so.p/gumexceptor.c.o gum/libfrida-gum-1.0.so.p/gumeventsink.c.o gum/libfrida-gum-1.0.so.p/gumheapapi.c.o gum/libfrida-gum-1.0.so.p/guminterceptor.c.o gum/libfrida-gum-1.0.so.p/guminvocationcontext.c.o gum/libfrida-gum-1.0.so.p/guminvocationlistener.c.o gum/libfrida-gum-1.0.so.p/gumkernel.c.o gum/libfrida-gum-1.0.so.p/gumleb.c.o gum/libfrida-gum-1.0.so.p/gumlibc.c.o gum/libfrida-gum-1.0.so.p/gummemory.c.o gum/libfrida-gum-1.0.so.p/gummemorymap.c.o gum/libfrida-gum-1.0.so.p/gummetalarray.c.o gum/libfrida-gum-1.0.so.p/gummetalhash.c.o gum/libfrida-gum-1.0.so.p/gummoduleapiresolver.c.o gum/libfrida-gum-1.0.so.p/gummodulemap.c.o gum/libfrida-gum-1.0.so.p/gumprintf.c.o gum/libfrida-gum-1.0.so.p/gumprocess.c.o gum/libfrida-gum-1.0.so.p/gumreturnaddress.c.o gum/libfrida-gum-1.0.so.p/gumstalker.c.o gum/libfrida-gum-1.0.so.p/arch-x86_gumx86writer.c.o gum/libfrida-gum-1.0.so.p/arch-x86_gumx86relocator.c.o gum/libfrida-gum-1.0.so.p/arch-x86_gumx86reader.c.o gum/libfrida-gum-1.0.so.p/arch-arm_gumarmwriter.c.o gum/libfrida-gum-1.0.so.p/arch-arm_gumarmrelocator.c.o gum/libfrida-gum-1.0.so.p/arch-arm_gumthumbwriter.c.o gum/libfrida-gum-1.0.so.p/arch-arm_gumthumbrelocator.c.o gum/libfrida-gum-1.0.so.p/arch-arm_gumarmreg.c.o gum/libfrida-gum-1.0.so.p/arch-arm64_gumarm64writer.c.o gum/libfrida-gum-1.0.so.p/arch-arm64_gumarm64relocator.c.o gum/libfrida-gum-1.0.so.p/arch-mips_gummipswriter.c.o gum/libfrida-gum-1.0.so.p/arch-mips_gummipsrelocator.c.o gum/libfrida-gum-1.0.so.p/backend-posix_gummemoryaccessmonitor-posix.c.o gum/libfrida-gum-1.0.so.p/backend-linux_gummemory-linux.c.o gum/libfrida-gum-1.0.so.p/backend-posix_gummemory-posix.c.o gum/libfrida-gum-1.0.so.p/backend-linux_gumprocess-linux.c.o gum/libfrida-gum-1.0.so.p/backend-posix_gumtls-posix.c.o gum/libfrida-gum-1.0.so.p/backend-posix_gumexceptor-posix.c.o gum/libfrida-gum-1.0.so.p/backend-elf_gumelfmodule.c.o gum/libfrida-gum-1.0.so.p/arch-x86_gumx86backtracer.c.o gum/libfrida-gum-1.0.so.p/backend-x86_gumcpucontext-x86.c.o gum/libfrida-gum-1.0.so.p/backend-x86_guminterceptor-x86.c.o gum/libfrida-gum-1.0.so.p/backend-x86_gumspinlock-x86.c.o gum/libfrida-gum-1.0.so.p/backend-x86_gumstalker-x86.c.o gum/libfrida-gum-1.0.so.p/backend-x86_gumstalker-x86-glue.S.o gum/libfrida-gum-1.0.so.p/backend-libunwind_gumunwbacktracer.c.o gum/libfrida-gum-1.0.so.p/backend-libdwarf_gumsymbolutil-libdwarf.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libfrida-gum-1.0.so -ldwarf -ldl -lz /usr/lib/libglib-2.0.so /usr/lib/libgobject-2.0.so /usr/lib/libgio-2.0.so /usr/lib/../lib/libffi.so /usr/lib/libcapstone.so /usr/lib/libunwind.so /usr/lib/libelf.so -Wl,--end-group
/usr/bin/ld: gum/libfrida-gum-1.0.so.p/backend-posix_gumtls-posix.c.o: in function `gum_tls_key_new':
/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/../gum/backend-posix/gumtls-posix.c:31: undefined reference to `pthread_key_create'
/usr/bin/ld: gum/libfrida-gum-1.0.so.p/backend-posix_gumtls-posix.c.o: in function `gum_tls_key_free':
/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/../gum/backend-posix/gumtls-posix.c:39: undefined reference to `pthread_key_delete'
/usr/bin/ld: gum/libfrida-gum-1.0.so.p/backend-posix_gumtls-posix.c.o: in function `gum_tls_key_get_value':
/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/../gum/backend-posix/gumtls-posix.c:45: undefined reference to `pthread_getspecific'
/usr/bin/ld: gum/libfrida-gum-1.0.so.p/backend-posix_gumtls-posix.c.o: in function `gum_tls_key_set_value':
/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/../gum/backend-posix/gumtls-posix.c:52: undefined reference to `pthread_setspecific'
collect2: error: ld returned 1 exit status
```
</details>

<details>
  <summary>2. frida-compile not found</summary>

```
[2/46] Generating gumjs-runtime with a custom command
FAILED: bindings/gumjs/gumquickscript-runtime.h bindings/gumjs/gumquickscript-objc.h bindings/gumjs/gumquickscript-java.h bindings/gumjs/gumv8script-runtime.h bindings/gumjs/gumv8script-objc.h bindings/gumjs/gumv8script-java.h bindings/gumjs/gumcmodule-runtime.h 
/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs/generate-runtime.py x86_64 /home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs /home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/gum /usr/include/capstone/capstone /usr/lib '' /home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/bindings/gumjs
Traceback (most recent call last):
  File "/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs/generate-runtime.py", line 336, in <module>
    subprocess.check_call([node_script_path("frida-compile"), "./runtime/entrypoint-quickjs.js", "-o", runtime] + quick_options, cwd=input_dir)
  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs/node_modules/.bin/frida-compile'
```
</details>

<details>
<summary>3. #include libdwarf.h fails</summary>

```
[2/53] Compiling C object gum/libfrida-gum-1.0.so.p/backend-libdwarf_gumsymbolutil-libdwarf.c.o
FAILED: gum/libfrida-gum-1.0.so.p/backend-libdwarf_gumsymbolutil-libdwarf.c.o 
cc -Igum/libfrida-gum-1.0.so.p -Igum -I../gum -I. -I.. -I../gum/arch-x86 -I../gum/arch-arm -I../gum/arch-arm64 -I../gum/arch-mips -Ilibs -I../libs -Ilibs/gum/heap -I../libs/gum/heap -Ilibs/gum/prof -I../libs/gum/prof -I../gum/backend-elf -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/capstone -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -include config.h '-DG_LOG_DOMAIN="Frida"' -D_GNU_SOURCE=1 -fPIC -pthread -MD -MQ gum/libfrida-gum-1.0.so.p/backend-libdwarf_gumsymbolutil-libdwarf.c.o -MF gum/libfrida-gum-1.0.so.p/backend-libdwarf_gumsymbolutil-libdwarf.c.o.d -o gum/libfrida-gum-1.0.so.p/backend-libdwarf_gumsymbolutil-libdwarf.c.o -c ../gum/backend-libdwarf/gumsymbolutil-libdwarf.c
../gum/backend-libdwarf/gumsymbolutil-libdwarf.c:19:10: fatal error: libdwarf.h: No such file or directory
   19 | #include <libdwarf.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```
</details>

<details>
<summary>4. gum not linked with libfrida-gum-heap </summary>

```
[1/46] Linking target libs/gum/heap/libfrida-gum-heap-1.0.so
FAILED: libs/gum/heap/libfrida-gum-heap-1.0.so 
cc  -o libs/gum/heap/libfrida-gum-heap-1.0.so libs/gum/heap/libfrida-gum-heap-1.0.so.p/meson-generated_.._.._.._.._gum_gumenumtypes.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumallocationblock.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumallocationgroup.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumallocationtracker.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumallocatorprobe.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumboundschecker.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumcobject.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumcobjecttracker.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/guminstancetracker.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumpagepool.c.o libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumsanitychecker.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libfrida-gum-heap-1.0.so '-Wl,-rpath,$ORIGIN/../../../gum' -Wl,-rpath-link,/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/gum gum/libfrida-gum-1.0.so -ldl -ldwarf -lz /usr/lib/libglib-2.0.so /usr/lib/libgobject-2.0.so /usr/lib/libgio-2.0.so /usr/lib/libcapstone.so -Wl,--end-group -pthread
/usr/bin/ld: libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumallocatorprobe.c.o: in function `gum_allocator_probe_class_init':
/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/../libs/gum/heap/gumallocatorprobe.c:211: undefined reference to `_gum_register_destructor'
/usr/bin/ld: libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumboundschecker.c.o: in function `replacement_calloc':
/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/../libs/gum/heap/gumboundschecker.c:399: undefined reference to `gum_memset'
/usr/bin/ld: libs/gum/heap/libfrida-gum-heap-1.0.so.p/gumboundschecker.c.o: in function `replacement_realloc':
/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/../libs/gum/heap/gumboundschecker.c:451: undefined reference to `gum_memcpy'
/usr/bin/ld: libs/gum/heap/libfrida-gum-heap-1.0.so: hidden symbol `gum_memcpy' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```
</details>

<details>
<summary> 5. FRIDA_VERSION causes error</summary>

```
[2/46] Compiling C object tests/gumjs/libgum-tests-gumjs.a.p/script.c.o
FAILED: tests/gumjs/libgum-tests-gumjs.a.p/script.c.o 
cc -Itests/gumjs/libgum-tests-gumjs.a.p -Itests/gumjs -I../tests/gumjs -Itests -I../tests -I../tests/stubs -Ibindings -I../bindings -Ibindings/gumjs -I../bindings/gumjs -I. -I.. -Igum -I../gum -I../gum/arch-x86 -I../gum/arch-arm -I../gum/arch-arm64 -I../gum/arch-mips -Ilibs -I../libs -Ilibs/gum/heap -I../libs/gum/heap -Ilibs/gum/prof -I../libs/gum/prof -I../gum/backend-elf -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/capstone -I/usr/include/v8 -I/usr/include/gio-unix-2.0 -I/usr/include/json-glib-1.0 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -include config.h '-DG_LOG_DOMAIN="Frida"' -D_GNU_SOURCE=1 -fPIC -pthread -std=c++11 -DV8_COMPRESS_POINTERS -MD -MQ tests/gumjs/libgum-tests-gumjs.a.p/script.c.o -MF tests/gumjs/libgum-tests-gumjs.a.p/script.c.o.d -o tests/gumjs/libgum-tests-gumjs.a.p/script.c.o -c ../tests/gumjs/script.c
cc1: warning: command-line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
In file included from ../tests/gumjs/script.c:10:
../tests/gumjs/script.c: In function ‘test_script_socket_connection_can_be_established_with_tls’:
../tests/gumjs/script.c:2706:35: error: expected ‘)’ before ‘FRIDA_VERSION’
 2706 |       "      'User-Agent: Frida/" FRIDA_VERSION "',"
      |                                   ^~~~~~~~~~~~~
../tests/gumjs/script-fixture.c:78:59: note: in definition of macro ‘COMPILE_AND_LOAD_SCRIPT’
   78 |     test_script_fixture_compile_and_load_script (fixture, SOURCE, \
      |                                                           ^~~~~~
[3/46] Generating gumjs-runtime with a custom command
```
</details>

<details>
<summary>6. Permission error</summary>

```
FAILED: bindings/gumjs/gumquickscript-runtime.h bindings/gumjs/gumquickscript-objc.h bindings/gumjs/gumquickscript-java.h bindings/gumjs/gumv8script-runtime.h bindings/gumjs/gumv8script-objc.h bindings/gumjs/gumv8script-java.h bindings/gumjs/gumcmodule-runtime.h 
/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs/generate-runtime.py x86_64 /home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs /home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/gum /usr/include/capstone/capstone /usr/lib '' /home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/buildir/bindings/gumjs
Traceback (most recent call last):
  File "/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs/generate-runtime.py", line 340, in <module>
    generate_runtime_quick("runtime", output_dir, "gumquickscript-runtime.h", input_dir, [runtime], quickcompile)
  File "/home/paschka/Projects/projektarbeit/prototype-frida/frida-complete/frida/frida-gum/bindings/gumjs/generate-runtime.py", line 30, in generate_runtime_quick
    subprocess.check_call([quickcompile, input_path, input_path_quick])
  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''
ninja: build stopped: subcommand failed.
```
</details>

**Comment by oleavr** [comment]
Please have a look at the build instructions [here](https://frida.re/docs/building/#gnulinux) – you definitely want to use our patched versions of the different dependencies. (We have patches that make our dependencies work better for our in-process dynamic lifetime constraints.)

**Comment by P-Sc** [comment]
I should have figured :man_facepalming:
Thanks!
